### ISSUE TITLE
Crash when holding tab in the :theme section

### ISSUE THREAD

**Issue by rp1231** [gavlig/kodiki#4]
If I go to the themes section using :theme and press and hold tab, the program crashes.
The same works fine in helix.

**Comment by gavlig** [comment]
Thanks for the report, i managed to repro on my side too.

**Comment by rp1231** [comment]
I have a list of other bugs as well
- Doesn't follow cursor settings defined in the config.toml (For eg. The insert mode doesn't show the bar cursor)
- Doesn't show all the theme colors (The `editor.cursor-shape` should have a yellow color in this theme)
  
<img width="718" alt="owKDH1i2Q1" src="https://github.com/gavlig/kodiki/assets/47380919/5c432114-1412-4be4-8a90-8660c31c4a6b">

- Colors are rendered noticeably duller than helix
- When Scrolling up and down using the cursor, the line numbers appear to have some kind of after image so they appear twice.

Didn't want to create a new issue for this as I don't know if you'd be interested in fixing all of these.
Posting this just in case you are interested.

Also have a couple of feature requests:
- Ability to run the program without a separate terminal window on windows
- Neovide like cursor animation

Thanks

**Comment by gavlig** [comment]
> Doesn't follow cursor settings defined in the config.toml (For eg. The insert mode doesn't show the bar cursor)
> Doesn't show all the theme colors (The editor.cursor-shape should have a yellow color in this theme)

Yeah, cursor is still under heavy development, i don't know yet how it will end up, so there is only bare minimum implemented for now. 

> Colors are rendered noticeably duller than helix

That is most likely postprocessing, it will be optional when i get to implementing any kind of options that are kodiki-specific, but we're not there yet.

> When Scrolling up and down using the cursor, the line numbers appear to have some kind of after image so they appear twice.

I couldnt repro that, could you make a video please?

> Ability to run the program without a separate terminal window on windows

Could you elaborate on that? Does it not launch when you double click executable?

> Neovide like cursor animation

i have a few of my own ideas to implement yet, but could you elaborate what kind of animations you have in mind? After checking their configuration i'd assume you're referring to the stretchy-interpolation thing from here https://neovide.dev/configuration.html#animation-length, am i right?


And thanks for your time and effort!

**Comment by rp1231** [comment]
Thanks for your answers.
The only question you seemed to have missed out on is the theme colors not showing up,
as shown in the screenshot.

Here is a video of the scrolling, the double numbers appear only when the cursor is at the extreme top or extreme bottom.
Also the strange thing is that I am not able to capture that using screen recording which is why I had to use my phone camera:

https://github.com/gavlig/kodiki/assets/47380919/599ec22e-b0d8-4e0d-aa9c-c8d28ea59257

Regarding the terminal opening with the program problem, I think that you might have uploaded the debug version of the program to the releases section. (Windows version)

Also I get this crash message on that terminal when I minimize kodiki.
```
gltf assets loaded!
font assets loaded!
all assets loaded!
thread 'Compute Task Pool (0)' panicked at C:\Users\gavlig\.cargo\registry\src\index.crates.io-6f17d22bba15001f\parry3d-0.13.5\src\query\clip\clip_aabb_line.rs:141:19:
Matrix index out of bounds.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (0)' panicked at C:\Users\gavlig\.cargo\git\checkouts\bevy-7d8a25fd14ce7172\b2e0894\crates\bevy_ecs\src\schedule\executor\multi_threaded.rs:459:45:
internal error: entered unreachable code: sending into a closed channel
thread 'Compute Task Pool (0)' panicked at C:\Users\gavlig\.cargo\git\checkouts\bevy-7d8a25fd14ce7172\b2e0894\crates\bevy_ecs\src\schedule\executor\multi_threaded.rs:194:60:
A system has panicked so the executor cannot continue.: RecvError
thread 'Compute Task Pool (0)' panicked at

```

**Comment by rp1231** [comment]
Also keep getting this message at the bottom of the screen saying 
`Language server not active for the current buffer`
Any way to activate the language server?

**Comment by gavlig** [comment]
Alright, there is a lot to unpack here.

> Also I get this crash message on that terminal when I minimize kodiki.

this crash i've seen a couple of times, but couldnt reproduce. Does it happen to you every time you minimize it?

> Regarding the terminal opening with the program problem

I doubt that since debug version is very slow, but i'll double check

> Here is a video of the scrolling,

Nice, thanks! looks like some kind of ghosting is going on there, i wonder if i dont have it or my eyes ignore it...

> The only question you seemed to have missed out on is the theme colors not showing up,
as shown in the screenshot.

I just bundled up my answer about cursor being a very WIP :) I don't know yet if i will keep supporting the color scheme for it (i might end up doing so too, we'll see)

> Any way to activate the language server?

That is a purely Helix thing, i can only refer you to its documentation: https://docs.helix-editor.com/languages.html#language-server-configuration

**Comment by rp1231** [comment]
> i have a few of my own ideas to implement yet, but could you elaborate what kind of animations you have in mind? After checking their configuration i'd assume you're referring to the stretchy-interpolation thing from here https://neovide.dev/configuration.html#animation-length, am i right?

Yes that's exactly what I was referring to.

**Comment by rp1231** [comment]
> this crash i've seen a couple of times, but couldnt reproduce. Does it happen to you every time you minimize it?

Yep, happens every time I minimize kodiki

> I just bundled up my answer about cursor being a very WIP :) I don't know yet if i will keep supporting the color scheme for it (i might end up doing so too, we'll see)

I was referring to the color of the text "editor.cursor-shape" and not the cursor color.

> That is a purely Helix thing, i can only refer you to its documentation: https://docs.helix-editor.com/languages.html#language-server-configuration

Hmm..... never had this message come up for me in helix before.... I'll check it out regardless. Thanks

**Comment by gavlig** [comment]
ah lol, i misundertood what you were showing on that screenshot. Ok, that might be due to your Helix installation being newer than what is used for Kodiki under the hood. That's a nice catch regardless, i'll try to keep this in mind to check later when i update my fork of Helix

**Comment by gavlig** [comment]
~~Hey, i've tried to repro the crash with :theme again and it doesnt happen anymore. Could you maybe share the source file you have open in the buffer that causes the crash for you?~~
Never mind, this is also a 100% repro on Windows

**Comment by gavlig** [comment]
found how to remove console on windows: https://bevy-cheatbook.github.io/platforms/windows.html#disabling-the-windows-console will make a build shortly

**Comment by gavlig** [comment]
added kodiki_0.1_x86_64_windows_no_console.7z to 0.1 release files, it will not produce a console in Windows when started

**Comment by rp1231** [comment]
Yep, it works !
Doesn't produce a console on windows anymore.
Thanks

Also, just out of curiosity, What os are you on?
And I read in the docs that you keep on forgetting whether you're in insert mode or not.
So you don't use the bar cursor for insert mode in either helix or vim?
It's a pretty dead giveaway for insert mode?

**Comment by gavlig** [comment]
> Also, just out of curiosity, What os are you on?

I use Linux, mostly Arch or its flavors. 

> So you don't use the bar cursor for insert mode in either helix or vim?

No, i guess both of them dont change the cursor type by default and i never bothered to investigate before.
If you're planning on using Kodiki and this is a blocker for you i can quickly hack something in to support that

**Comment by rp1231** [comment]
> No, i guess both of them dont change the cursor type by default and i never bothered to investigate before. If you're planning on using Kodiki and this is a blocker for you i can quickly hack something in to support that.

My bad, I thought that helix changed the cursor type by default. But it's just nvim and vim that do.

And no need to rush for the quick hack as I won't be able to use it as a daily driver anyways till the minimize bug is fixed.

Thanks

**Comment by gavlig** [comment]
Crash with :theme is fixed in b0dcc7e6b3d1a084f349e3982c66c21dad18a63a for latest binaries see [release 0.11](https://github.com/gavlig/kodiki/releases/tag/0.11)

**Comment by rp1231** [comment]
Thanks for the quick fixes!
The only bug remaining from this thread is the ghosting of the numbers when scrolling as was shown in the window.
Also don't seem to be able to close the window with the close button now.
The only way to exit seems to be `:q!`

**Comment by gavlig** [comment]
Yeah, the ghosting will have to wait for a bigger update probably, if it
stays in new engine version I'll see what I can do. (and I suspect I don't
have it or maybe I can't see it on my monitor)
As for the not closing check the message in the bottom when closing doesn't
work, most likely you have unsaved buffers. But since you didn't notice
that it means I might need to make that more obvious
